name: Build & Deploy
run-name: Initiated by ${{ github.actor }}
# Run on main branch with tag v*.*.*
on:
  push:
    branches:
      - main
    # tags:
    #   - v*.*.*
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.12.0
      - run: npm install
      - run: vsce package
      # Read the version from the package.json file
      - run: echo "VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
      # Upload the VSIX file as an artifact with version number
      - uses: actions/upload-artifact@v2
        with:
          name: commit-extension-${{ env.VERSION }}
          path: *.vsix