name: Build & Deploy
run-name: Initiated by ${{ github.actor }}
# Run on main branch with tag v*.*.*
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.12.0
      - run: npm install
      - run: npm install -g vsce
      - run: vsce package
      # Read the version from the package.json file
      - run: echo "VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
      # Upload the VSIX file as an artifact with version number
      - uses: actions/upload-artifact@v3
        with:
          name: commit-extension-${{ env.VERSION }}
          path: ./*.vsix

  # Create a release with the version number
  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      # Download the VSIX file from the artifact
      - uses: actions/download-artifact@v2
        with:
          name: commit-extension-${{ env.VERSION }}
          path: ./
      
      # Upload the VSIX file to the Github release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}