name: Build & Deploy
run-name: Initiated by ${{ github.actor }}
# Run on main branch with tag v*.*.*
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.12.0
      # Install dependencies
      - run: npm install
      - run: npm install -g vsce
      # Build the extension
      - run: vsce package
        env:
          COMMIT_GRAPHQL_API_URL : ${{ secrets.COMMIT_GRAPHQL_API_URL }}
          COMMIT_API_BASE_URL : ${{ secrets.COMMIT_API_BASE_URL }}
          COMMIT_APP_BASE_URL : ${{ secrets.COMMIT_APP_BASE_URL }}
          COMMIT_AUTH0_DOMAIN : ${{ secrets.COMMIT_AUTH0_DOMAIN }}
          COMMIT_CLIENT_ID : ${{ secrets.COMMIT_CLIENT_ID }}
      # Upload the VSIX file as an artifact with version number
      - uses: actions/upload-artifact@v3
        with:
          name: commit-extension
          path: ./*.vsix

  # Create a release with the version number
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download the VSIX file from the artifact
      - uses: actions/download-artifact@v2
        with:
          name: commit-extension
          path: ./
      
      # Upload the VSIX file to the Github release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}