name: Build & Deploy
run-name: Initiated by ${{ github.actor }}
# Run on main branch with tag v*.*.*
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        default: 'v0.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.12.0
      # Install dependencies
      - run: npm install
      - run: npm install -g vsce
      # Build the extension
      - run: vsce package
        env:
          COMMIT_GRAPHQL_API_URL : https://api.commit.dev/graphql
          COMMIT_API_BASE_URL : https://api.commit.dev
          COMMIT_APP_BASE_URL : https://app.commit.dev
          COMMIT_AUTH0_DOMAIN : https://commitdev.auth0.com
          COMMIT_CLIENT_ID : ${{ secrets.COMMIT_CLIENT_ID_STAGING }}

      # Rename the VSIX file to the version number
      - name: Rename VSIX file
        run: mv *.vsix commit-extension-${{ github.event.inputs.tag }}.vsix
      # Upload the VSIX file as an artifact with version number
      - uses: actions/upload-artifact@v3
        with:
          name: commit-extension-${{ github.event.inputs.tag }}
          path: ./*.vsix

  # Create a release with the version number
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download the VSIX file from the artifact
      - uses: actions/download-artifact@v2
        with:
          name: commit-extension-${{ github.event.inputs.tag }}
          path: ./
      
      # Check if the release already exists
      - name: Check if release exists
        id: check_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If the release already exists then exit
      - name: Exit if release exists
        if: ${{ steps.check_release.outputs.exists == 'true' }}
        run: exit 0

      # Upload the VSIX file to the Github release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}